<a href="https://colab.research.google.com/github/vpavankalyan/Data_Science_projects/blob/master/BreastCancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importing the libraries

In [1]:
import pandas as pd
import numpy as np

## Importing the dataset

In [16]:
dataset = pd.read_csv('/content/breast-cancer-wisconsin.data',header=None)

In [17]:
dataset.head()

0   1   2   3   4   5   6   7   8   9   10
0  1000025   5   1   1   1   2   1   3   1   1   2
1  1002945   5   4   4   5   7  10   3   2   1   2
2  1015425   3   1   1   1   2   2   3   1   1   2
3  1016277   6   8   8   1   3   4   3   7   1   2
4  1017023   4   1   1   3   2   1   3   1   1   2

##TAKING CARE OF MISSING DATA

In [19]:
dataset = dataset.replace('?',np.NaN)

In [20]:
X = dataset.iloc[:,1:-1].values
y = dataset.iloc[:,-1].values

In [26]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy = 'mean')
#imputer.fit(x[:,1:])
X[:,:] = imputer.fit_transform(X[:,:])


## Splitting the dataset into the Training set and Test set

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [28]:
print(X_train)

[[1.0 1.0 1.0 ... 1.0 1.0 1.0]
 [1.0 6.0 8.0 ... 5.0 7.0 1.0]
 [4.0 1.0 1.0 ... 3.0 1.0 1.0]
 ...
 [1.0 3.0 3.0 ... 7.0 2.0 1.0]
 [3.0 1.0 4.0 ... 3.0 1.0 1.0]
 [6.0 2.0 1.0 ... 7.0 1.0 1.0]]


In [29]:
print(y_train)

[2 4 2 2 2 4 2 4 2 2 2 2 2 4 2 2 2 2 2 2 2 4 2 2 4 4 2 2 2 2 2 4 4 2 2 4 4
 4 4 4 4 2 2 2 2 4 2 2 2 2 2 2 2 4 2 4 4 4 4 2 2 2 2 2 4 4 4 2 4 2 4 2 4 2
 4 2 2 2 2 2 2 2 2 2 2 2 2 4 2 2 2 4 2 2 2 2 2 2 2 4 2 4 4 2 2 4 4 2 2 2 2
 2 2 4 4 4 2 2 2 4 2 4 2 2 2 2 4 2 4 2 2 4 2 2 4 2 2 2 4 2 4 2 2 4 2 2 2 2
 2 4 4 2 4 2 4 2 2 2 2 4 2 2 2 2 2 4 4 2 2 4 4 2 4 2 2 4 2 4 2 4 2 2 4 2 2
 4 2 2 2 2 4 4 2 4 2 2 4 2 4 2 4 4 2 2 4 2 2 4 2 2 2 4 4 2 2 2 2 4 2 4 2 2
 4 4 2 2 2 2 2 4 4 2 4 4 2 4 2 4 4 4 2 2 2 4 2 2 4 2 4 2 2 2 2 2 2 2 4 4 4
 2 4 2 2 2 2 2 2 2 2 2 2 2 2 4 4 2 4 2 2 4 2 2 2 2 2 2 4 2 4 2 4 2 2 4 4 4
 4 2 2 4 2 2 4 2 4 2 2 4 2 2 2 4 4 2 2 2 2 4 2 4 4 2 4 2 2 2 4 2 4 2 4 4 4
 2 2 2 4 2 2 2 2 2 2 2 4 2 2 2 4 2 2 4 2 2 2 2 4 2 4 2 2 2 4 2 4 4 4 2 4 2
 4 2 2 2 2 4 4 2 4 2 2 4 4 2 4 4 2 2 4 2 4 2 2 2 4 2 2 2 2 2 2 2 2 2 2 2 2
 4 2 4 2 2 2 2 2 2 2 2 2 2 2 4 4 2 4 4 2 2 2 2 4 2 2 2 2 2 2 2 2 2 4 2 2 2
 4 4 2 2 2 4 2 4 2 2 2 2 4 4 4 2 4 2 2 2 2 2 4 4 2 4 2 2 2 2 4 2 2 4 4 4 4
 4 2 4 2 2 4 4 2 2 4 4 4 

## Training the Logistic Regression model on the Training set

In [30]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0)
clf.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

## Predicting the Test set results

In [31]:
y_pred = clf.predict(X_test)

In [33]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [4 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 4]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 4]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]
 [2 2]
 [4 4]
 [2 2]
 [2 2]
 [2 2]
 [4 4]
 [4 4]]


## Making the Confusion Matrix

In [34]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[91,  1],
       [ 2, 46]])

In [35]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9785714285714285